# Generated by Django 4.0.4 on 2022-08-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snipit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=240)),
                ('snip_title', models.CharField(max_length=240)),
                ('language_code', models.CharField(max_length=2000)),
                ('short_description', models.CharField(max_length=240)),
            ],
        ),
    ]
